services:
  # App con React
  vite:
    container_name: vite
    user: "${UID}:${GID}"
    image: node:22-alpine
    working_dir: /app
    volumes: 
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks: [default]
    tty: true


  # PHP-FPM para backend
  php:
    container_name: php
    user: "${UID}:${GID}"
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1 # Recarga automática de archivos en desarrollo
    networks: [default]
    restart: unless-stopped
  

  # Nginx para servir la app + PHP
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./backend:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks: [default]
    depends_on:
      - php
      - vite
    restart: unless-stopped



# Configuración de red personalizada
networks:
  default:
    name: dev_curso
    driver: bridge

    
